if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ComplexHeatmap")

install.packages("circlize")
install.packages("ggplot2")
install.packages("tictoc")
install.packages("Matrix")
install.packages("uwot")
install.packages("stringr")
install.packages("data.table")
install.packages("PRROC")
install.packages("sads")
install.packages("Rcpp")
install.packages("optparse")